name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["stable"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: go build ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["stable"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: go test ./... -v

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["stable"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Go Vet
        run: go vet ./...

      - name: Gofmt Check
        run: |
          files=$(find . -type f -name '*.go')
          test -z "$(gofmt -l $files)"
